name: Deploy Nginx to Docker Hub and ArgoCD

on:
  push:
    branches:
      - main  # main 브랜치에 push하면 실행됨

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-app:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nginx-app:latest

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/nginx-deployment nginx=${{ secrets.DOCKER_USERNAME }}/nginx-app:latest --namespace=default
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - name: Trigger ArgoCD Sync
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }} --insecure
          argocd app sync nginx-app

