apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-sample-deployment
  namespace: eks-sample-app
  labels:
    app: eks-sample-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: eks-sample-app
  template:
    metadata:
      labels:
        app: eks-sample-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: sample
        image: 495599735720.dkr.ecr.ap-southeast-1.amazonaws.com/my-nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
      nodeSelector:
        kubernetes.io/os: linux

